### PR TITLE
Require dhall >= 1.35.0 for dhall-bash 1.0.33

### PR DESCRIPTION
**Pull request by felixonmars**
It doesn't build with dhall 1.34.0:

```
[1 of 1] Compiling Dhall.Bash       ( src/Dhall/Bash.hs, dist/build/Dhall/Bash.dyn_o )

src/Dhall/Bash.hs:364:28: error:
    Not in scope: ‘Dhall.Core.fieldSelectionLabel’
    Module ‘Dhall.Core’ does not export ‘fieldSelectionLabel’.
    |
364 |     go e@(Field (Union m) (Dhall.Core.fieldSelectionLabel -> k)) =
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### CODE REVIEW

**Review by sjakobi — APPROVED** [review]
Thanks!

**Comment by sjakobi** [comment]
I've made a corresponding Hackage revision.
