### PR TITLE
Relax bounds

### PR DESCRIPTION
**Pull request by TeofilC**
This relaxes most bounds as indicated by cabal outdated.
I've checked and all the tests pass. This allows building the library with GHC 9.10.

The only thing I've left behind is lsp as it seems like there's some breaking changes there and there's an existing PR for that.

In order to build with GHC-9.10, you will also need the following allow-newers added to cabal.project:
```
allow-newer: lucid:*, lsp:*, hnix:*, lens-family-th:*, dependent-sum-template:*
```

### CODE REVIEW

**Comment by mmhat** [comment]
LGTM; Thank you @TeofilC !

**Comment by georgefst** [comment]
Could we please get a corresponding Hackage revision?

**Comment by Gabriella439** [comment]
Oops!  Sorry about that

I believe these should all be published as matching revisions to Hackage now

**Comment by TeofilC** [comment]
Thanks!

**Comment by Gabriella439** [comment]
you're welcome!

**Comment by georgefst** [comment]
> I've checked and all the tests pass.

It's an easy mistake to make (we need better tooling!), but it appears that tests weren't actually run with these new versions. At the very least, `time-1.14` is actually _not_ compatible:
```console
$ cabal build lib:dhall --constraint=time==1.14 # requires removing other entries from `cabal.project`
Build profile: -w ghc-9.10.1 -O1
In order, the following will be built (use -v for more details):
 - dhall-1.42.2 (lib) (first run)
Preprocessing library for dhall-1.42.2...
Building library for dhall-1.42.2...
[32 of 77] Compiling Dhall.Syntax.Instances.Lift ( src/Dhall/Syntax/Instances/Lift.hs, /home/gthomas/code/dhall-haskell/dist-newstyle/build/x86_64-linux/ghc-9.10.1/dhall-1.42.2/build/Dhall/Syntax/Instances/Lift.o, /home/gthomas/code/dhall-haskell/dist-newstyle/build/x86_64-linux/ghc-9.10.1/dhall-1.42.2/build/Dhall/Syntax/Instances/Lift.dyn_o ) [Data.Time package changed]
src/Dhall/Syntax/Instances/Lift.hs:24:1: error: [GHC-59692]
    Duplicate instance declarations:
      instance Lift Time.Day
        -- Defined at src/Dhall/Syntax/Instances/Lift.hs:24:1
      instance [safe] Lift Time.Day
        -- Defined in ‘time-1.14:Data.Time.Calendar.Days’
   |
24 | deriving instance Lift Time.Day
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error: [Cabal-7125]
Failed to build dhall-1.42.2.
```

This case is fixed by https://github.com/dhall-lang/dhall-haskell/pull/2647.

We ought to test the others and publish Hackage revisions re-tightening the bounds where appropriate.

**Comment by Gabriella439** [comment]
@ysangkok: I uploaded a new release of dhall.  Hopefully that should fix the remaining issues, but let me know if I missed something

**Comment by ysangkok** [comment]
@Gabriella439 : Thank you. In addition, dhall-{bash,json,yaml} could easily be fixed with new revisions. I have just verified that they all work on GHC 9.12 if I pass `--allow-newer`.
