### ISSUE TITLE
dhall-1.42.0 fails to build in Stackage Nightly

### ISSUE THREAD

**Issue by juhp** [dhall-lang/dhall-haskell#2516]
```
       Building library for dhall-1.42.0..
       [69 of 77] Compiling Dhall.TH
       
       /var/stackage/work/unpack-dir/unpacked/dhall-1.42.0-d29671176e59c6861b5d2ff055de0a8160793e10de281c46a8279821c9efc88d/src/Dhall/TH.hs:274:38: error:
           • Couldn't match type: flag0 -> Syntax.TyVarBndr flag0
                            with: Syntax.TyVarBndr ()
             Expected: [Syntax.TyVarBndr ()]
               Actual: [flag0 -> Syntax.TyVarBndr flag0]
           • In the third argument of ‘DataD’, namely ‘params’
             In the expression:
               DataD [] name params Nothing constructors derivingClauses
             In the first argument of ‘pure’, namely
               ‘[DataD [] name params Nothing constructors derivingClauses]’
           |
       274 |                 [pure [DataD [] name params Nothing constructors derivingClauses]] <>
           |                                      ^^^^^^
```

**Comment by sjakobi** [comment]
I can reproduce this with GHC 9.0.1, 9.0.2, 9.2.4 and 9.4.4, and have made a corresponding revision on Hackage: https://hackage.haskell.org/package/dhall-1.42.0/revisions/

The issue was apparently introduced in https://github.com/dhall-lang/dhall-haskell/pull/2506 or an earlier change to that file (CC @ndwarshuis).

I don't understand why CI didn't catch this issue though – I thought the `ubuntu-latest` and `windows-latest` jobs are using GHC 9.0.1.

**Comment by sjakobi** [comment]
> I don't understand why CI didn't catch this issue though – I thought the `ubuntu-latest` and `windows-latest` jobs are using GHC 9.0.1.

These jobs don't make use of the installed "Haskell environment" though – they use `stack` with `lts-18.18` which is based on GHC-8.10.7.

I guess it's high time to add CI with a recent version of GHC.

**Comment by alaendle** [comment]
@sjakobi - to enable `dhall-1.42.0` in nightly we also need relaxed bounds for `template-haskell` and `unix-compat`.

template-haskell-2.19.0.0 ([changelog](http://hackage.haskell.org/package/template-haskell-2.19.0.0/changelog)) is out of bounds for:
- [ ] dhall-1.42.0 (>=2.13.0.0 && < 2.17). Gabriella Gonzalez <GenuineGabriella@gmail.com> @Gabriella439. Used by: library


unix-compat-0.7 ([changelog](http://hackage.haskell.org/package/unix-compat-0.7/changelog)) (Mitchell Rosen <mitchellwrosen@gmail.com> @mitchellwrosen) is out of bounds for:
- [ ] dhall-1.42.0 (>=0.4.2 && < 0.7). Gabriella Gonzalez <GenuineGabriella@gmail.com> @Gabriella439. Used by: library

**Comment by chenrui333** [comment]
any update on this thread?

**Comment by ysangkok** [comment]
It was fixed in https://github.com/dhall-lang/dhall-haskell/pull/2542

**Comment by Gabriella439** [comment]
Yeah, I'm closing this as I'm fairly confident this is fixed in `master` and will be fixed in the next release of `dhall`.  (I've been meaning to release it soon, but have just been very busy, but I hope to get to cutting the release this Sunday)
