### PR TITLE
Add Dhall.Deriving module for deriving-via helpers

### PR DESCRIPTION
**Pull request by akrmn**
I've been working on adapting @parsonsmatt's [blog post](https://www.parsonsmatt.org/2020/02/04/mirror_mirror.html) on reflection and encoding via applied to Aeson to work on Dhall. I'm happy with my current implementation, though I'd still like to add a few tests and possibly improve documentation with a guide or something similar. I'd also like to gather some feedback before merging.
- [x] Write a guide?

### CODE REVIEW

File: dhall/src/Dhall/Deriving.hs [hunk 1]
```diff
@@ -0,0 +1,212 @@
...
+{-# LANGUAGE FlexibleContexts     #-}
+{-# LANGUAGE KindSignatures       #-}
+{-# LANGUAGE PolyKinds            #-}
+{-# LANGUAGE ScopedTypeVariables  #-}
+{-# LANGUAGE TypeApplications     #-}
+{-# LANGUAGE TypeOperators        #-}
+{-# LANGUAGE TypeSynonymInstances #-}
+{-# LANGUAGE UndecidableInstances #-}
+
+module Dhall.Deriving
```
Comment (Gabriel439) [inline dhall/src/Dhall/Deriving.hs]: I think the only thing really missing is a doctest and/or example illustrating how this works.  CI will require a module documentation header here anyway, so that's probably the best place to add it

Comment (akrmn) [reply dhall/src/Dhall/Deriving.hs]: done!

**Comment by sjakobi** [comment]
Could you add the new module to `dhall/doctest/Main.hs` so the doctests are actually run?

**Comment by akrmn** [comment]
Hi @sjakobi, I tried adding the `Deriving` module to `dhall/doctest/Main.hs`, but I wanted to test locally first. I've been struggling to get the development environment working on my machine (macOS 10.15.3). `cabal` worked fine for writing the module `Dhall.Deriving`, but when trying to run `cabal new-test dhall:doctest` I got a few errors like this:
```
dhall-haskell/dhall/ghc-src/Dhall/Import/HTTP.hs:38:5: error:
     error: function-like macro 'MIN_VERSION_http_client' is not defined
   |
38 | #if MIN_VERSION_http_client(0,5,0)
   |     ^
#if MIN_VERSION_http_client(0,5,0)
    ^
```

I tried building with stack too, but `stack test dhall:doctest` gave me the same errors. Nix is out of the question on my version of macOS, I believe (happy to be corrected, though!), so I also tried building inside an Ubuntu VM. In the VM, running `nix-shell` didn't provide the executables for cabal or ghc, so I couldn't do anything inside the nix shell. 

Finally, `nix-build` did run, but I got some errors in the doctests, the biggest of which is that `DerivingVia` wasn't available before `ghc-8.6.1`, while the default compiler is set to `ghc843` in `nix/shared.nix`, so I'll probably need a check on the ghc version (which I'm not sure how to write).

Whew. I think I've exhausted my options here, so I'd really appreciate your help, if possible. Thanks!

**Comment by sjakobi** [comment]
Well, while working doctests are totally neat, the setup and ergonomics do leave a lot to be desired! :/

I always use `stack` to run doctests, which with this patch

```patch
--- a/dhall/doctest/Main.hs
+++ b/dhall/doctest/Main.hs
@@ -38,6 +38,7 @@ main = do
 
             -- , prefix </> "src"
             , "-i" <> (prefix </> "src")
+            , prefix </> "src/Dhall/Deriving.hs"
             , prefix </> "src/Dhall/Tags.hs"
             , prefix </> "src/Dhall/Tutorial.hs"
             ]
```

…gives me:

<details>

```
$ stack test dhall:doctest
dhall-1.30.0: unregistering (local file changes: doctest/Main.hs)
dhall> build (lib + test)
Preprocessing test suite 'doctest' for dhall-1.30.0..
Building test suite 'doctest' for dhall-1.30.0..
[1 of 1] Compiling Main
Linking .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/doctest/doctest ...
Preprocessing library for dhall-1.30.0..
Building library for dhall-1.30.0..
dhall> copy/register
Installing library in /home/simon/src/dhall-haskell/.stack-work/install/x86_64-linux/2cd7226215d912742b9bc19685d6004f3f9e5cacfed4b485b2ba1dd5d309906e/8.6.5/lib/x86_64-linux-ghc-8.6.5/dhall-1.30.0-KKKBcbpJFlQ70XgsDWAseO
Installing executable dhall in /home/simon/src/dhall-haskell/.stack-work/install/x86_64-linux/2cd7226215d912742b9bc19685d6004f3f9e5cacfed4b485b2ba1dd5d309906e/8.6.5/bin
Registering library for dhall-1.30.0..
dhall> test (suite: doctest)
                   
Progress 1/2: dhallLoaded package environment from /tmp/stack27734/test-ghc-env
Loaded package environment from /tmp/stack27734/test-ghc-env
Loaded package environment from /tmp/stack27734/test-ghc-env
Loaded package environment from /tmp/stack27734/test-ghc-env
Loaded package environment from /tmp/stack27734/test-ghc-env

when making flags consistent: warning:
    -O conflicts with --interactive; -O ignored.
/home/simon/src/dhall-haskell/dhall/src/Dhall/Deriving.hs:241: failure in expression `:{
newtype Name = Name { getName :: Text }
<BLANKLINE>
data Font = Arial | ComicSans | Helvetica | TimesNewRoman
<BLANKLINE>
data Person = Person
  { personName :: Name
  , personFavoriteFont :: Font
  }
:}'
expected: 
 but got: 
          <interactive>:23:1: error: parse error on input ‘<’

/home/simon/src/dhall-haskell/dhall/src/Dhall/Deriving.hs:298: failure in expression `:{
deriving stock instance Generic Name
deriving stock instance Generic Font
deriving stock instance Generic Person
<BLANKLINE>
deriving anyclass instance FromDhall Name
deriving anyclass instance FromDhall Font
deriving anyclass instance FromDhall Person
:}'
expected: 
 but got: 
          <interactive>:38:1: error: parse error on input ‘<’

/home/simon/src/dhall-haskell/dhall/src/Dhall/Deriving.hs:399: failure in expression `:{
deriving via Codec (Field (CamelCase <<< DropPrefix "person")) Person instance FromDhall Person
deriving via Codec (Constructor TitleCase) Font instance FromDhall Font
deriving via Codec (SetSingletonConstructors Bare) Name instance FromDhall Name
:}'
expected: 
 but got: 
          <interactive>:49:1: error:
              Illegal standalone deriving declaration
                Use StandaloneDeriving to enable this extension
          
          <interactive>:49:1: error:
              Illegal deriving strategy: via
              Use DerivingVia to enable this extension

Examples: 220  Tried: 207  Errors: 0  Failures: 3
                   
dhall> Test suite doctest failed
Completed 2 action(s).
Test suite failure for package dhall-1.30.0
    doctest:  exited with: ExitFailure 1
Logs printed to console
```

</details>

I use Ubuntu BTW.

With `cabal` you're probably running into this issue: https://github.com/sol/doctest/issues/245

You may want to try some of the workarounds described there.

Also, l think most people eventually managed to get the doctests working with `stack`, so there are a few things you could try:

1. Check that you have the most recent `stack` version installed.
2. Try running `stack build dhall` before `stack test dhall:doctest` to ensure the GHC environment files are written.

Regarding GHC compatibility: The first thing to try would be to move the problematic doctests behind CPP. I usually refer to https://guide.aelve.com/haskell/cpp-vww0qd72#item-fkuvztqe for that.

If that doesn't work out (I'm not sure how well `doctest` interacts with CPP), we can conditionally disable the `doctest` suite in `dhall.cabal`.

This is all a bit annoying and tricky, so please do let me know in case you get stuck! :)

**Comment by akrmn** [comment]
Hey again @sjakobi! Thanks for your tips! Eventually I got `stack` working on macOS, though I had to fiddle with `stack.yaml` (almost matching your #1695 PR, I just noticed). It took me a few tries but it seems to be working now, the only odd thing is setting a couple of extensions here and there. 
Regarding compatibility, I think CPP might be overkill for this module since it's not really useful before `ghc-8.6.5`. I learned about Cabal conditionals by looking at `dhall.cabal` and they seem like a good fit for this case.
Again, thanks a lot for the help!

**Comment by sjakobi** [comment]
I'm glad you got it working! :)

I haven't yet reviewed `Dhall.Deriving` properly, but I wanted to ask you to add a reference to the new module from the main `Dhall` module, to make this stuff more easy to discover.

**Comment by akrmn** [comment]
Gladly!

**Comment by akrmn** [comment]
Hi again @sjakobi, is there anything I need to do to get the hydra check to run?

**Comment by sjakobi** [comment]
Hydra does run (and fail), but the GitHub interface doesn't show it. It would be great if we could get that fixed properly! :/

For now you can find the Hydra results for this PR at https://hydra.dhall-lang.org/jobset/dhall-haskell/1700.

**Comment by akrmn** [comment]
I see! Thanks!

**Comment by akrmn** [comment]
Finally got it to build! Is it okay if I merge it?

**Comment by sjakobi** [comment]
Well done! Sorry for the delay with my review! I'll try to get it done until tomorrow evening at the latest.

**Comment by akrmn** [comment]
Oh don’t worry at all. Thanks for the help!

File: dhall/src/Dhall/Deriving.hs [hunk 2]
```diff
@@ -0,0 +1,515 @@
...
+{-# LANGUAGE TypeSynonymInstances #-}
+{-# LANGUAGE UndecidableInstances #-}
+
+{-| Newtypes for writing customizable 'FromDhall' and 'ToDhall' instances
+    through the DerivingVia strategy.
+
+    Inspired by Matt Parson's blog post
+    [Mirror Mirror: Reflection and Encoding Via](https://www.parsonsmatt.org/2020/02/04/mirror_mirror.html),
+    but applied to Dhall instead of JSON.
+-}
```
Comment (sjakobi) [inline dhall/src/Dhall/Deriving.hs]: Please mention that the module is only included with GHC >= 8.6.

File: dhall/src/Dhall/Deriving.hs [hunk 3]
```diff
@@ -0,0 +1,515 @@
...
+
+module Dhall.Deriving
+  (
+    -- * Introduction
+    -- $introduction
+
+    -- * Writing FromDhall instances by hand
+    -- $instancesByHand
```
Comment (sjakobi) [inline dhall/src/Dhall/Deriving.hs]: These motivating sections are very good, but also quite long. I fear that some users with short attention spans (like myself) might give up before they find out how _this module_ can be used.

So maybe put `$derivingVia` at the top, move the other sections to the bottom of the page, but reference them from that top section? Just an idea…

File: dhall/doctest/Main.hs [hunk 4]
```diff
@@ -38,6 +46,11 @@ main = do
 
             -- , prefix </> "src"
             , "-i" <> (prefix </> "src")
+#ifdef MIN_VERSION_GLASGOW_HASKELL
+#if MIN_VERSION_GLASGOW_HASKELL(8,6,1,0)
```
Comment (sjakobi) [inline dhall/doctest/Main.hs]: I don't think I've ever seen these pragmas before. Why not use the conventional

```
#if __GLASGOW_HASKELL__ >= 806
```

instead?

File: dhall/src/Dhall.hs [hunk 5]
```diff
@@ -1109,9 +1109,14 @@ pair l r = Decoder extractOut expectedOut
...
 
-    This class auto-generates a default implementation for records that
+    This class auto-generates a default implementation for types that
     implement `Generic`.  This does not auto-generate an instance for recursive
     types.
+
+    The default instance can be tweaked using 'genericAutoWith' and custom
+    'InterpretOptions', or using
+    [DerivingVia](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#extension-DerivingVia)
+    and 'Dhall.Deriving.Codec' from 'Dhall.Deriving'.
```
[the remark this answers is not in the document]
Comment (akrmn) [reply dhall/src/Dhall.hs]: well spotted, thanks!

File: dhall/src/Dhall/Deriving.hs (hunk 3 above)
Comment (akrmn) [reply dhall/src/Dhall/Deriving.hs]: yeah I wasn't sure how to structure it. I'll look into that later today, but your suggestion sounds good

File: dhall/doctest/Main.hs (hunk 4 above)
Comment (akrmn) [reply dhall/doctest/Main.hs]: Found it [here](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/phases.html#standard-cpp-macros). I used that one because DerivingVia was introduced in a patchlevel version (per [this](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#deriving-via)), and I thought this looked ~better~ less bad than nesting `__GLASGOW_HASKELL__ ` and `__GLASGOW_HASKELL_PATCHLEVEL1__`

Comment (sjakobi) [reply dhall/doctest/Main.hs]: Oh! I think you'll find that pretty much every extension was added in minor version X.Y.1, but that's only because 1 is the starting minor version number for official releases. Just

     #if __GLASGOW_HASKELL__ >= 806

should be fine.

Comment (akrmn) [reply dhall/doctest/Main.hs]: Ah! That makes sense, thanks!

- [ ] replace pragma

File: dhall/src/Dhall/Deriving.hs (hunk 2 above)
Comment (akrmn) [reply dhall/src/Dhall/Deriving.hs]: - [ ] mention that the module is only included with GHC >= 8.6.

File: dhall/src/Dhall/Deriving.hs (hunk 3 above)
Comment (akrmn) [reply dhall/src/Dhall/Deriving.hs]: - [ ] reorder documentation sections

Comment (akrmn) [reply dhall/src/Dhall/Deriving.hs]: I tried your suggestion but I didn't like the result, since (surprisingly) the Haddock story for linking to headings or documentation chunks isn't there. Instead, I linked to the `$derivingVia` section from the header. Let me know what you think.

File: dhall/src/Dhall/Deriving.hs [hunk 6]
```diff
@@ -0,0 +1,548 @@
...
+
+    Inspired by Matt Parson's blog post
+    [Mirror Mirror: Reflection and Encoding Via](https://www.parsonsmatt.org/2020/02/04/mirror_mirror.html),
+    but applied to Dhall instead of JSON.
+
+    This module is intended to be used with
+    [DerivingVia](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#extension-DerivingVia)
+    so it's only available for GHC >= v8.6.1.
+
+    Check "Dhall.Deriving#derivingVia" if you want to see this module in action.
```
Comment (sjakobi) [inline dhall/src/Dhall/Deriving.hs]: The way this anchor link is rendered is a bit confusing:

image

```suggestion
    Check the section /Letting DerivingVia do the work/ if you want to see this module in action.
```

File: dhall/src/Dhall/Deriving.hs (hunk 3 above)
Comment (sjakobi) [reply dhall/src/Dhall/Deriving.hs]: Fair enough! Should be easy to change if we later come up with a better idea!

File: dhall/src/Dhall/Deriving.hs (hunk 6 above)
Comment (akrmn) [reply dhall/src/Dhall/Deriving.hs]: yeah, I wasn't sure about this one, it seems like a choice between having the right name but no link or the link but with the confusing name (why would you go to the same module you're already reading??). I'll try to reword it so we can have both.
