### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [dhall-lang/dhall-haskell#2339]
```
dhall-json                > /tmp/stack-dc895ad1c31fa393/dhall-json-1.7.8/src/Dhall/JSON.hs:539:47: error:
dhall-json                >     • Couldn't match type: HashMap.HashMap Text Value
dhall-json                >                      with: Data.Aeson.KeyMap.KeyMap Value
dhall-json                >       Expected: Aeson.Object
dhall-json                >         Actual: HashMap.HashMap Text Value
dhall-json                >     • In the first argument of ‘Object’, namely ‘(HashMap.fromList ys)’
dhall-json                >       In the first argument of ‘return’, namely
dhall-json                >         ‘(Object (HashMap.fromList ys))’
dhall-json                >       In a stmt of a 'do' block: return (Object (HashMap.fromList ys))
dhall-json                >     |
dhall-json                > 539 |                         return (Aeson.Object (HashMap.fromList ys))
dhall-json                >     |                                               ^^^^^^^^^^^^^^^^^^^
dhall-json                > 
dhall-json                > /tmp/stack-dc895ad1c31fa393/dhall-json-1.7.8/src/Dhall/JSON.hs:584:47: error:
dhall-json                >     • Couldn't match type: HashMap.HashMap Text Value
dhall-json                >                      with: Data.Aeson.KeyMap.KeyMap Value
dhall-json                >       Expected: Aeson.Object
dhall-json                >         Actual: HashMap.HashMap Text Value
dhall-json                >     • In the first argument of ‘Object’, namely ‘(HashMap.fromList ys)’
dhall-json                >       In the first argument of ‘return’, namely
dhall-json                >         ‘(Object (HashMap.fromList ys))’
dhall-json                >       In a stmt of a 'do' block: return (Object (HashMap.fromList ys))
dhall-json                >     |
dhall-json                > 584 |                         return (Aeson.Object (HashMap.fromList ys))
dhall-json                >     |                                               ^^^^^^^^^^^^^^^^^^^
dhall-json                > 
dhall-json                > /tmp/stack-dc895ad1c31fa393/dhall-json-1.7.8/src/Dhall/JSON.hs:636:35: error:
dhall-json                >     • Couldn't match type: HashMap.HashMap k1 Value
dhall-json                >                      with: Data.Aeson.KeyMap.KeyMap Value
dhall-json                >       Expected: Aeson.Object
dhall-json                >         Actual: HashMap.HashMap k1 Value
dhall-json                >     • In the first argument of ‘Object’, namely ‘fields’
dhall-json                >       In the expression: Object fields
dhall-json                >       In an equation for ‘omitNull’:
dhall-json                >           omitNull (Object object)
dhall-json                >             = Object fields
dhall-json                >             where
dhall-json                >                 fields = HashMap.filter (/= Null) (fmap omitNull object)
dhall-json                >     |
dhall-json                > 636 | omitNull (Object object) = Object fields
dhall-json                >     |                                   ^^^^^^
dhall-json                > 
dhall-json                > /tmp/stack-dc895ad1c31fa393/dhall-json-1.7.8/src/Dhall/JSON.hs:638:39: error:
dhall-json                >     • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap’
dhall-json                >                      with ‘HashMap.HashMap k’
dhall-json                >       Expected: HashMap.HashMap k Value
dhall-json                >         Actual: Data.Aeson.KeyMap.KeyMap Value
dhall-json                >     • In the second argument of ‘HashMap.filter’, namely
dhall-json                >         ‘(fmap omitNull object)’
dhall-json                >       In the expression: HashMap.filter (/= Null) (fmap omitNull object)
dhall-json                >       In an equation for ‘fields’:
dhall-json                >           fields = HashMap.filter (/= Null) (fmap omitNull object)
dhall-json                >     • Relevant bindings include
dhall-json                >         fields :: HashMap.HashMap k Value
dhall-json                >           (bound at src/Dhall/JSON.hs:638:5)
dhall-json                >     |
dhall-json                > 638 |     fields =HashMap.filter (/= Null) (fmap omitNull object)
dhall-json                >     |                                       ^^^^^^^^^^^^^^^^^^^^
dhall-json                > 
dhall-json                > /tmp/stack-dc895ad1c31fa393/dhall-json-1.7.8/src/Dhall/JSON.hs:655:42: error:
dhall-json                >     • Couldn't match type: HashMap.HashMap k0 Value
dhall-json                >                      with: Data.Aeson.KeyMap.KeyMap Value
dhall-json                >       Expected: Aeson.Object
dhall-json                >         Actual: HashMap.HashMap k0 Value
dhall-json                >     • In the first argument of ‘Object’, namely ‘fields’
dhall-json                >       In the expression: Object fields
dhall-json                >       In the expression: if null fields then Null else Object fields
dhall-json                >     |
dhall-json                > 655 |     if null fields then Null else Object fields
dhall-json                >     |                                          ^^^^^^
dhall-json                > 
dhall-json                > /tmp/stack-dc895ad1c31fa393/dhall-json-1.7.8/src/Dhall/JSON.hs:657:40: error:
dhall-json                >     • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap’
dhall-json                >                      with ‘HashMap.HashMap k’
dhall-json                >       Expected: HashMap.HashMap k Value
dhall-json                >         Actual: Data.Aeson.KeyMap.KeyMap Value
dhall-json                >     • In the second argument of ‘HashMap.filter’, namely
dhall-json                >         ‘(fmap omitEmpty object)’
dhall-json                >       In the expression: HashMap.filter (/= Null) (fmap omitEmpty object)
dhall-json                >       In an equation for ‘fields’:
dhall-json                >           fields = HashMap.filter (/= Null) (fmap omitEmpty object)
dhall-json                >     • Relevant bindings include
dhall-json                >         fields :: HashMap.HashMap k Value
dhall-json                >           (bound at src/Dhall/JSON.hs:657:5)
dhall-json                >     |
dhall-json                > 657 |     fields = HashMap.filter (/= Null) (fmap omitEmpty object)
dhall-json                >     |                                        ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by sjakobi** [comment]
The recent versions of `dhall-json` have an upper bound `aeson < 1.6`. Therefore I assume you were using `--allow-newer` and aware of the possibility of incompatibilities.

On `master`, `dhall-json` was made compatible in https://github.com/dhall-lang/dhall-haskell/commit/becb4468c27aeacfc7f713c8d83b27957b43b307.

**Comment by Gabriel439** [comment]
This will be fixed once we publish a new release.  See: https://github.com/dhall-lang/dhall-haskell/pull/2340
